---
title: "Registration of deaths and cases of incfection"
output: html_document
date: "2025-05-13"
subtitle: "Scatterplots of death registraions and cases of incfection derived from data registered in Berlingske Tidende"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Creating the workspace

### Creating folders
```{r dir.create, warning=FALSE}
dir.create("data")
dir.create("figures")
```

### Loading relevant libraries
```{r libraries, warning=FALSE}
library(tidyverse)
library(tidytext)
library(ggwordcloud)
library(urltools)
```


### Loading dataset
```{r loading dataset, warning=FALSE}
kolera_numbers <- read_csv2("data/kolera_copenhagen_1853.csv",na="NA")

```

### Showing the data
```{r glimpse, warning=FALSE}
glimpse(kolera_numbers, warning=FALSE)

```





# Creating scatterplots

### Creating graph over New deaths
```{r New deaths, warning=FALSE}
kolera_numbers %>%
  ggplot(aes(Date,y=new_deaths, color=new_deaths))+
  geom_point()+
  geom_smooth(method = "loess", color="hotpink")+
  geom_point()+
  theme_bw()+
  scale_color_gradient(low="black", high="hotpink")+
  labs(
    title = "New deaths during the cholera epidemic in Copenhagen in 1853",
    subtitle = "Dataregistrations from Berlingske Tidende",
    x = "Date",
    y = "Registrations")

ggsave("figures/scatterplot_new_deaths.png", width = 18, height = 13, units = "cm", bg = "white")

```

### Creating our graph over total death
```{r creating our graph over new death, warning=FALSE}
kolera_numbers %>%
  ggplot(aes(Date,y=total_deaths, color=total_deaths))+
  geom_point()+
  geom_smooth(method = "loess", color="hotpink")+
  geom_point()+
  theme_bw()+
  scale_color_gradient(low="black", high="hotpink")+
  labs(
    title = "Total deaths during the cholera epidemic in Copenhagen in 1853",
    subtitle = "Dataregistrations from Berlingske Tidende",
    x = "Date",
    y = "Registrations"
  )

ggsave("figures/scatterplot_total_deaths.png", width = 18, height = 13, units = "cm", bg = "white")

```



### Creating graph over new cases
```{r scatterplots, warning=FALSE}
kolera_numbers %>%
  ggplot(aes(Date,y=new_cases, color=new_cases))+
  geom_point()+
  geom_smooth(method = "loess", color="darkblue")+
  geom_point()+
  theme_bw()+
  scale_color_gradient(low="darkblue", high="lightblue")+
  labs(
    title = "New cases during the cholera epidemic in Copenhagen in 1853",
    subtitle = "Dataregistrations from Berlingske Tidende",
    x = "Date",
    y = "Registrations"
  )

ggsave("figures/scatterplot_new_cases.png", width = 18, height = 13, units = "cm", bg = "white")

```





### Creating graph over total cases
```{r creating graph over new cases, warning=FALSE}
kolera_numbers %>%
  ggplot(aes(Date,y=total_cases, color=total_cases))+
  geom_point()+
  geom_smooth(method = "loess", color="darkblue")+
  geom_point()+
  theme_bw()+
  scale_color_gradient(low="darkblue", high="lightblue")+
  labs(
    title = "Total cases during the cholera epidemic in Copenhagen in 1853",
    x = "Date",
    y = "Registrations"
  )

ggsave("figures/scatterplot_total_cases.png", width = 18, height = 13, units = "cm", bg = "white")

```





